### ISSUE TITLE
Lorem Badges

### ISSUE THREAD

**Issue by MaximRouiller** [Azure/functionschallenge#1]
Or maybe I should learn Latin. ;-)

![image](https://cloud.githubusercontent.com/assets/209384/20279732/b3d255e2-aa77-11e6-8f9d-57f90f8f8216.png)

**Comment by fashaikh** [comment]
:) Fixed. Thanks @MaximRouiller !

**Comment by MaximRouiller** [comment]
Confirmed as fix. Now I have to reason to learn latin and can focus on Azure Functions. 😄
