### ISSUE TITLE
Incorrect error message when Sort Array returns 999 values

### ISSUE THREAD

**Issue by graham-sportsmgmt** [Azure/functionschallenge#10]
I had an error in my Step 1 code that missed the first value, so only 999 values were actually stored in my Table.  Although my Step 2 code was correctly sorting the 999 values the error message returned was "Processed your message. The returned array was not sorted.."  (yes, there really were two periods at the end of the sentence).

**Comment by fashaikh** [comment]
Thanks ! I'll enhance the error reporting to do better validation and send a clearer message . It can be difficult to debug if one integer is missing in a 1000.

**Comment by fashaikh** [comment]
I've add the checks
