### ISSUE TITLE
Sort Array - Step 1 - Submitting a new URL doesn't trigger new request to Function

### ISSUE THREAD

**Issue by PlagueHO** [Azure/functionschallenge#14]
I had a bug in my Sort Array step 1 function the first time I submitted it to the Azure Functions Challenge. The function reported that it succeeded, but it had not actually saved the table record (so Step 2 would never succeed - this may relate to #13).

I fixed the issue and resubmitted the URL, but Step 1 does not trigger a request to my new function. I've updated the default key for the function, so the old URL won't work. The monitor logs for the function also confirm that the Azure Functions Challenge has not hit the new code (I also made the new function report the datetime of the request back in the JSON output).

I've even gone as far as to delete and recreate my Step 1 function with a different name, but old URL is still used no matter what.

So I can't proceed any further with the challenges. :cry:

**Comment by fashaikh** [comment]
Sorry this is happened, and thanks for reporting it.
I will reset your profile for the challenge in about an hour.

**Comment by fashaikh** [comment]
I have reset your usercontext, so you shoudl be able to start from step1 in Challenge3.

**Comment by PlagueHO** [comment]
Awesome! Thank you @fashaikh 

Also, great job with this learning tool - it is very useful.

**Comment by fashaikh** [comment]
Thanks for the kind words @PlagueHO  ! 
Glad you like it .

**Comment by PlagueHO** [comment]
Thanks @fashaikh ! :grin:
