### ISSUE TITLE
Sort Array - Step 1 - Re-submitting doesn't trigger new request to Function

### ISSUE THREAD

**Issue by danielhalse** [Azure/functionschallenge#15]
I believe I have a similar issue to #13 and #14 .
The first step completed once but it used the same key as my test data so mixed up data in the Azure table.
I deleted the table but cannot re-trigger step 1 to re-load the data into the Azure table.

I receive the following message when submitting Step 2 for the Sort Array task:
UserContextId:377d370d-49ae-4778-9a58-4c321266877d, 
UniqueId:bf20822a-4261-4b19-a363-0e63698f7eaa. 
StackTrace
System.NullReferenceException: Object reference not set to an instance of an object. at Submission#0.ArraysEqual(Int32[] a1, Int32[] a2) in D:\home\site\wwwroot\Shared\Shared.csx:line 210 at CallSite.Target(Closure , CallSite , Type , Int32[] , Object ) at Submission#0.d__15.MoveNext() in :line 70

**Comment by fashaikh** [comment]
Sorry you are facing this @danielhalse . I have reset your profile so you shoudl be able to submit from step 1 in challenge 3. 
I will investigate the issue as well.

**Comment by JoeMayo** [comment]
Same problem here - monitor logs don't indicate that the function was called.
