### ISSUE TITLE
Sorting Functions

### ISSUE THREAD

**Issue by aantillonl** [Azure/functionschallenge#16]
UserContextId:3e633533-f392-4b73-925f-84cc999cfc11, 
UniqueId:78785512-43f1-4ee8-8dc1-6d302b275f92. 

First timer to all this functions/serverless stuff, i've implemented 2 functions from the sorting challenge. 

In the first step i do get the OK message, but that is not very significant since there is no response expected, however, i do notice that when i put the URL of my function in the validation form in the challenge page, no new entries are added to my azure storage account, I would expect to see a new entry from your validation process.

Second, the next step, obviously fails, since there is no data in the storage account to be validated

PD, as some other guys, i also validated myself using the sample key from the example, i deleted it afterwards though.

**Comment by fashaikh** [comment]
Sorry about this.
I have reset challenge 3. Can you try from step 1 again.

**Comment by fashaikh** [comment]
I've also added a fix allow retrying previous steps, and better error handling on step1
