### ISSUE TITLE
Azure Functions Challenge Sort Array Step 2 fails verification

### ISSUE THREAD

**Issue by brianobr** [Azure/functionschallenge#17]
The first step passes fine, but the second one gives me a "Let's Try Again" message. Input the new key in my table and get the expected output:
{"key":"033e0975-f3ee-4fe5-930b-23c5b889fd2c","ArrayOfValues":[2038545,4395810,7729280,10777117,13896776,14293060,...]

Any idea on how to get started resolving this?

**Comment by fashaikh** [comment]
Looking. I see this error in step1 , `The 'code' query parameter provided in the HTTP request did not match the expected value.` .  Could you check the code is correct . or [reset it ](http://stackoverflow.com/questions/40746945/azure-function-function-keys)if needed. I got the same error via POSTMAN. Meanwhile,  I'll update the step1 validation check to include this condition as well.

**Comment by brianobr** [comment]
Thank you. I ended up recreating the function for the challenge; resetting the code likely would have fixed the problem. I appreciate your help.
