### ISSUE TITLE
Typo https://functionschallenge.azure.com/functions

### ISSUE THREAD

**Issue by DavidDeSloovere** [Azure/functionschallenge#18]
There's a typo on the https://functionschallenge.azure.com/functions page.
It's in this sentence

> If you haven't taken the opporunity to setup a Function App yet, use the buttons to the right to get your environment setup.

**Comment by fashaikh** [comment]
Thanks for reporting this ! Will get this updated soon.

**Comment by fashaikh** [comment]
Fixed the typo .
