### ISSUE TITLE
More details link in chrome is prefixed by unsafe:

### ISSUE THREAD

**Issue by DavidDeSloovere** [Azure/functionschallenge#19]
The link for downloading the result in prefixed by "unsafe:>"
When I click the link, an empty tab opens with this url, after removing "unsafe:>" I can download the file. I would expect the file to be downloaded immediately.

> unsafe:>https://challengeinvokelogs.blob.core.windows.net/outcontainer/10289ea8-cacd-4619-8443-dce48ee6645f?sv=2015-12-11&sr=b&sig=LTScDmYJsm8XSabdBIQ7xToSQSo2crVl40o6Dwjyaa0%3D&se=2017-01-10T09%3A19%3A07Z&sp=r

![image](https://cloud.githubusercontent.com/assets/352626/21496350/15f0eae6-cc1e-11e6-96d7-2279af27e5b1.png)

**Comment by fashaikh** [comment]
Thanks for reporting this !
Yes the unsafe link is a side effect of the eom sanitization in one of the angular libraries we use. Will come up with a better way to display the validation logs.
