### ISSUE TITLE
Functions Challenge issue on submission

### ISSUE THREAD

**Issue by ship2moon** [Azure/functionschallenge#2]
I have participated on Functions Challenge and I submitted my solution in:
https://functionspingpong.azurewebsites.net/api/HttpTriggerCSharp1

I tested my code using POSTMAN and I get a proper response as expected. But when submitting the solution, I get this error saying:

*_Lets try again.

. We were unable to validate the function.
Please file an issue here, if you do not recognise the stack trace below : https://github.com/Azure/functionschallenge/issues/new with 
UserContextId:e66251b1-a291-4845-8112-53624e9f532d, 
UniqueId:a9c6d064-96f6-447f-be60-2d6e06700ecb. 
StackTrace
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'string' does not contain a definition for 'pong' at CallSite.Target(Closure , CallSite , Object ) at Submission#0.d__15.MoveNext() in :line 48_*

**Comment by fashaikh** [comment]
Sorry about the challenge not being clearer. 
Could you make sure you are returning the right Content-Type
if I  `return req.CreateResponse(HttpStatusCode.OK,JsonConvert.SerializeObject(pongResponse));`  the Response is sent as `text` and interpreted as `String`. 
if I `return req.CreateResponse(HttpStatusCode.OK,pongResponse);`  it is sent and interpreted as `json`
where 
`var pongResponse = new {
        pong = <incomingGuid>
    };`
