### ISSUE TITLE
Submission failure

### ISSUE THREAD

**Issue by brianobr** [Azure/functionschallenge#20]
I tried submitting an answer for part 2 of Challenge 3. I get this message:
================
Lets try again. 
. We were unable to validate the function.
Please file an issue here, if you do not recognise the stack trace below : https://github.com/Azure/functionschallenge/issues/new with 
UserContextId:b0ca338a-0ee5-40da-a3e1-f009c2e37ae5, 
UniqueId:81367cc7-3a1b-44ce-bb3b-232d8fade92a. 
StackTrace
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference at CallSite.Target(Closure , CallSite , Object ) at Submission#0.d__15.MoveNext() in :line 70
====================
I also see no log information about the webhook being triggered at all.

**Comment by fashaikh** [comment]
It is a function code issue. `The 'code' query parameter provided in the HTTP request did not match the expected value.`   If you retry, it should show the error. 
If you reset the code or create a different function it should work.

**Comment by fashaikh** [comment]
Code Reset instructions are here: http://stackoverflow.com/questions/40746945/azure-function-function-keys . Alternately you can just create a new function and use its url
