### ISSUE TITLE
The 'code' query parameter provided in the HTTP request did not match the expected value

### ISSUE THREAD

**Issue by ponarunkumar** [Azure/functionschallenge#21]
While the test run was successful with Azure functions console, the challenge submission returned the following error.
![image](https://cloud.githubusercontent.com/assets/6130502/21592086/5e27eff8-d0d8-11e6-8a75-2f0b2adfdd51.png)

{
  "IsValid": false,
  "Message": "Your function returned an error:{\r\n  \"Message\": \"The 'code' query parameter provided in the HTTP request did not match the expected value.\"\r\n}",
  "FunctionUrl": "https://Functions5a92df57.azurewebsites.net/api/pingpongJS?code=3a7352e349e24937e0337c23ad54e2ca8ced30f0",
  "InputData": "{\r\n  \"ping\": \"29c0f2e2-2618-4da2-918c-c1f884be7bea\"\r\n}",
  "OutputData": "{\r\n  \"Message\": \"The 'code' query parameter provided in the HTTP request did not match the expected value.\"\r\n}",
  "HttpStatusCode": null,
  "UTCTimeStamp": "2017-01-02T15:38:14.497371Z",
  "UniqueId": "de0c024b-b844-483a-84f6-40f4340dc187",
  "UserContextId": "123",
  "Request": "{\r\n  \"FunctionUrl\": \"https://Functions5a92df57.azurewebsites.net/api/pingpongJS?code=3a7352e349e24937e0337c23ad54e2ca8ced30f0\",\r\n  \"UniqueId\": \"de0c024b-b844-483a-84f6-40f4340dc187\",\r\n  \"UserContextId\": \"123\"\r\n}"
}

**Comment by fashaikh** [comment]
Sorry this is happening @ponarunkumar . Could you reset the code using these steps in 
#17  . Also I am curious of the steps you took that triggered this since the code needing to get reset has happened a few times now.

**Comment by fashaikh** [comment]
Closing this issue for now. Please reopen if this still persists.
