### ISSUE TITLE
We were unable to validate the function

### ISSUE THREAD

**Issue by sachabruttin** [Azure/functionschallenge#22]
I tried to submit an answer for Challenge 4 GitHub Deploy. 
I get this message:

> We were unable to validate the function.
> Please file an issue here, if you do not recognise the stack trace below : https://github.com/Azure/functionschallenge/issues/new with 
> UserContextId:f3bd684e-0f80-4aa9-ba39-224bce428793, 
> UniqueId:0b9dd1ce-38a6-4b29-8f3e-53f7e5356a1e. 
> StackTrace
> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'functioncallengedeploy.azurewebsites.net' at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context) at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar) --- End of inner exception stack trace --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Submission#0.d__5.MoveNext() in D:\home\site\wwwroot\Shared\Shared.csx:line 42 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at CallSite.Target(Closure , CallSite , Object ) at Submission#0.d__15.MoveNext() in :line 33

I get correct response from the Function usingPostman... 

```
{
  "SubscriptionId": "edited..."
}
```

**Comment by fashaikh** [comment]
Thanks for reporting this !  `The remote name could not be resolved: 'functioncallengedeploy.azurewebsites.net'`  suggests the dns settings had not propagated to the validation machine. 
I see you tried multiple times for about 10  minutes, and but the url would not resolve on our end. I will follow up to see why there was a delay.

I checked and the webhook works correctly. now  Could you retry ?

**Comment by sachabruttin** [comment]
Thanks Faiz.
I retried and it works well.
