### ISSUE TITLE
Challenge 4 has no code to show, no idea how to pass it

### ISSUE THREAD

**Issue by hukhuk** [Azure/functionschallenge#23]
So there's not sample input/output availble for challenge 4. The "hint" looks like it was meant for the challenge 2. 
I tried a solution for challenge 2, as well as returning just an empty OK, but I get an error message saying "the output didn't match the input" or something like that (I removed he app service already, so can't check right now). More details shows that the input data is actually an empty object, so I'm not quite sure what I'm supposed to return.

**Comment by fashaikh** [comment]
Thanks for reporting it @hukhuk . I'll update the hints for challenge 4.

For challenge 4 you need to deploy the functionapp from the github repos using the arm templates provided (Links in the blue buttons). For this you'll need an existing azure subscription or a need to create a new one .

**Comment by fashaikh** [comment]
I've updated the hint to 
```javascript

Click on one of the blue Deploy Solution buttons above.
This challenge requires an Azure account, so if you''ve been using Try Functions up until this point you will need to sign up for a Free Trial

``` 
It wont show in your usercontext though. If you need it updated for your account I'll need your your usercontextid  . It will the guid in this network view:
![image](https://cloud.githubusercontent.com/assets/2650941/21907955/acd5740e-d8c6-11e6-9a96-cae43c0f4e89.png)
