### ISSUE TITLE
Sort Array Step 1

### ISSUE THREAD

**Issue by thomyg** [Azure/functionschallenge#24]
Hi!

I try to submit my function for step 1. The data gets stored in my table, but when I try returning:

return req.CreateResponse(HttpStatusCode.OK);

I get an error that my Json response IS empty.

If I change it to the value that is published in your hint section:

return req.CreateResponse(HttpStatusCode.OK, "Sorted and added!");

Here I get the error that my Json response IS NOT empty.

Everything works fine on the storage side, so what do I miss? thx.

**Comment by fashaikh** [comment]
Sorry @thomyg, you were facing this issue. You will need to return the text mentioned in this case. It is helpful to ensure that a good handshake has taken place.

**Comment by thomyg** [comment]
Sorry I don't manage to get this work @fashaikh . Everytime I return some text I get back that my response isn't ready, if I return an empty response I get an error because of that.

Right now I'm using the code from the hint section as is, and still I get an error.

**Comment by fashaikh** [comment]
Can you share your `UserContextId` by looking at the network trace. 
Alternately you can send me the  email id you used to sign into the challenge site  at this email address `websuppt at microsoft dot com`
