### ISSUE TITLE
The ping-pong example...

### ISSUE THREAD

**Issue by mminhaz** [Azure/functionschallenge#25]
I am trying to do ping-pong example. This is my code - I got the test working. But trying to submit it is giving me exception - I am completely confused. BTW the hint code provided does not work, so I fixed it as follows, which works for Test on the Function page.

The function is in here: https://mominhazfunction1.azurewebsites.net/api/GenericWebhookCSharp1?code=ijNqoq2NlK9iMtKVT5UQwEOC6EkeCFnOmtYKT87fzR9N09Q5OaIJdQ==
Exception: 

#r "Newtonsoft.Json"

using System;
using System.Net;
using Newtonsoft.Json;

public static async Task<HttpResponseMessage> Run(HttpRequestMessage req, TraceWriter log)
{
	log.Info($"Webhook was triggered!");

    string reqStr = await req.Content.ReadAsStringAsync();
    dynamic jsonContent = JsonConvert.DeserializeObject(reqStr);

	if (jsonContent?.ping == null) {
                HttpResponseMessage response1 = new HttpResponseMessage(HttpStatusCode.BadRequest);
                var resp = new
                {
                    error = "Please pass a ping guid to pingback"
                };

                response1.Content = new StringContent(resp.ToString());
                return response1;
	}

	var pongResponse = new {
		pong =  jsonContent?.ping
	};

    string strOut = JsonConvert.SerializeObject(pongResponse);
    HttpResponseMessage response = new HttpResponseMessage(HttpStatusCode.OK);
    response.Content = new StringContent(strOut);            

    return response;
}

**Comment by fashaikh** [comment]
Sorry this is happening to you.
I checked and the hint rendering indeed removes a couple of casts to <object> previously. Thanks for pointing it out ! Will investigate.

Also, I tried the above url. It is returning a response type header of 'text/plain' . Please set the response type or `application/json`  or use the updated hint below.

`Exception:System.Net.Http.UnsupportedMediaTypeException: No MediaTypeFormatter is available to read an object of type 'Object' from content with media type 'text/plain'.`
 
The error should also be visible in the logs link in the results modal that opens up. 

```javascript

#r "Newtonsoft.Json"

using System;
using System.Net;
using Newtonsoft.Json;

public static async Task<object> Run(HttpRequestMessage req, TraceWriter log)
{
	log.Info($"Webhook was triggered!");
	dynamic jsonContent = await req.Content.ReadAsAsync<object>();
	log.Info($"requestBody: {JsonConvert.SerializeObject(jsonContent)}");

	if (jsonContent?.ping == null) {
		return req.CreateResponse(HttpStatusCode.BadRequest, new {
			error = "Please pass a ping guid to pingback"
		});
	}
	var pongResponse = new {
		pong = jsonContent?.ping
	};

	return req.CreateResponse(HttpStatusCode.OK,pongResponse);
}
```

**Comment by fashaikh** [comment]
BTW I've added proper escaping so the missing code in the hints should show up for new users.
