### ISSUE TITLE
Array Sort - Step 2

### ISSUE THREAD

**Issue by codapus-co** [Azure/functionschallenge#26]
Hi!
I am trying to submit my function for step 2, but I am getting again and again the same message: "Processed your message. The returned array was not sorted.."

But the array seems to be sorted.
[64a9c215-9591-4a80-90ec-17c66ce061f5.txt](https://github.com/Azure/functionschallenge/files/829450/64a9c215-9591-4a80-90ec-17c66ce061f5.txt)

Thanks in advance!

**Comment by fashaikh** [comment]
hey @codapus-co . I looked into it. 
The output response only has 20 integers out of the 1000 that were initially  sent in Step 1.
That said I was expecting the error message to say `Your response returned 20 integers. Expecting 1000` . 
Currently the function is returning an empty array.  Please let me know when its returning the 1000 integers that were seeded. You can also reseed the values from step1 if needed.

**Comment by codapus-co** [comment]
Ok! That's great! Thank you for your time and effort! I found my bug! Sorry for wasting your time!
