### ISSUE TITLE
Sort Array Part 2

### ISSUE THREAD

**Issue by matrixgoh** [Azure/functionschallenge#27]
Hi!
I am also trying to submit my function for step 2, but I am getting again and again the same message: "Processed your message. The returned array was not sorted.."

But I have check the log file the result is sorted and have 999 rows in Azure Table.

[c9242ecc-813f-4375-a432-5043fcf8f88c.txt](https://github.com/Azure/functionschallenge/files/949660/c9242ecc-813f-4375-a432-5043fcf8f88c.txt)

Thanks.

**Comment by fashaikh** [comment]
Thanks for reporting this. I have added a patch to report if the returned numbers aren't equal to the previously provided numbers (1000) in this case. I think you are past this stage now. so I 'll close this and attend to the new issue you 've opened
