### ISSUE TITLE
Get error message "We were unable to validate the function."

### ISSUE THREAD

**Issue by matrixgoh** [Azure/functionschallenge#28]
Hi, I'm getting error exception below when I submit SortArray step 2. 

UserContextId:949a1be1-777c-4c2d-a5ea-d35a75991657, 
UniqueId:7ba9ca2e-f759-4bae-93c4-a25539177984. 
StackTrace
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'string' does not contain a definition for 'ToObject' at CallSite.Target(Closure , CallSite , Object ) at Submission#0.d__15.MoveNext() in :line 49

**Comment by fashaikh** [comment]
The data seems to be getting returned as a string

```javascript
 "{\"key\":\"8394f532-2643-48e6-928c-f16021031922\",\"ArrayOfValues\":[519128,3911507,7806295,11719744,.......2146939180]}"
```

is getting returned, while 

```javascript
{"key":"2eca724e-85b7-4127-812e-f4e9b9192021","ArrayOfValues":[1265395,5693083.....2144150707,2146802037]}

```
 is expected for json input.


I suggest creating a Challenge2Input object in your return function like this before returning, and let me know

```javascript
    var challenge3Message = new Challenge3Message{key = inputmsg.key, ArrayOfValues = JsonConvert.DeserializeObject<int []>(c3input?.ArrayOfValues) };
    return req.CreateResponse(HttpStatusCode.OK, challenge3Message);
```

For reference you can compare the response to this POST on 
`https://codechallengetest.azurewebsites.net/api/challenge3TestFunction2?code=ey7opx7q3jm2i65mp5w2ke29svt011c2jwmmvb1hsxg2b7qfr50ixfdpzcezkf5ye9xtn1giudi`
Body:
` { "key" : "2eca724e-85b7-4127-812e-f4e9b9192021" }`
Header:
`Content-Type:application/json`
