### ISSUE TITLE
Sort Array Part 2 - Not Sorted Error

### ISSUE THREAD

**Issue by KennyLowe** [Azure/functionschallenge#29]
Hello! 

The validation keeps telling me that the array is not sorted, but it is:/ I have attached the output file, all 1000 entities seem to be there, are sorted in order, and the appropriate key is included. Only thing I can see is that HTTP response is null, but HttpStatusCode.OK is being sent?

[e2f9bb6a-dc7c-4ff0-8573-ed312ae93ec0.txt](https://github.com/Azure/functionschallenge/files/1001478/e2f9bb6a-dc7c-4ff0-8573-ed312ae93ec0.txt)

**Comment by KennyLowe** [comment]
I recreated both functions and re-ran, and all worked fine. Most likely something I did wrongly caused this, closing the issue.

**Comment by fashaikh** [comment]
Thanks @KennyLowe  Happy hacking !
