### ISSUE TITLE
Azure Function Challenge : Sort Array : Step 2 Exception

### ISSUE THREAD

**Issue by ghost** [Azure/functionschallenge#3]
Sort Array : Step 2 : failed and raised the following exception.

UserContextId:6dd232d2-50d7-4b52-af59-5e90f3970f65, 
UniqueId:17710816-8bac-49b5-a443-c056044e4b6b. 
StackTrace
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: The best overloaded method match for 'Newtonsoft.Json.JsonConvert.DeserializeObject(string)' has some invalid arguments at CallSite.Target(Closure , CallSite , Type , Object ) at Submission#0.d__15.MoveNext() in :line 49

Testing the function from within Azure Function App returns Status : 200 OK and returns the sorted array in JSON format. Tested with following key:
{
	"key": "5a64e301-df34-4679-bf37-8c2b8eedfe2a",
}

**Comment by fashaikh** [comment]
Thanks @jaywalia888  for reporting this !
There was a parsing bug in our validation. I have updated it, and tested your function with it as well . Could you retry and let me know if this still fails for you ?
