### ISSUE TITLE
Submitting a valid solution to "Decipher Text" fails with "No response data received from your function" message

### ISSUE THREAD

**Issue by anderaus** [Azure/functionschallenge#30]
Submitting my answer to the "Decipher text" challenge returns error message "No response data received from your function".

The function works as expected when testing in Postman and in the Azure portal.

https://azurefunctionschallengenorway.azurewebsites.net/api/DecipherText
(supports POST only)

**Comment by fashaikh** [comment]
When I call into it via Postman it gives a 403 forbidden. Typically it means the auth level on the function isn't public. If so please provide the key in the Url 
something like: 
`https://test.azurewebsites.net/api/challenge2TestFunction?code=999yq8xjbc4utncqqc52q28dinumyp2e4xusn9nixv5hzlr1grionnnetztmv8r48z9ex50cnmi`

**Comment by anderaus** [comment]
Thanks for your reply, @fashaikh, but did you test the function by **post**ing the body given in the challenge?

I just retested it and it still works in Postman, as you can see here:

![image](https://user-images.githubusercontent.com/1311807/27102165-9152f48c-5084-11e7-8a30-aa970e42ba78.png)

But when actually submitting the solution I get this error:

![image](https://user-images.githubusercontent.com/1311807/27102206-adfcfd4e-5084-11e7-8c3b-837dec7b4a11.png)

**Comment by fashaikh** [comment]
I did and it gives the 403 error. Are you able to run that from another computer ?

![image](https://user-images.githubusercontent.com/2650941/27103131-83bb212a-503c-11e7-918f-5be0147b8d8a.png)

**Comment by anderaus** [comment]
Thanks again. I'm returning a 403 if the key  doesn't match the one in the challenge. That's probably a bad interpretation of the task on my hand. Still, try submitting with the key from the challenge, as seen in my screenshot, and you will hopefully be able to reproduce the error.

**Comment by fashaikh** [comment]
I see. If you look at the `More details here`  link it'll show the `key` we are using to call your function.
Its `3ca605ae-b52d-46be-8b04-ba4d5ba81d7f` . You need to accept that key and return he decrypted value with that `key` in the response. 
Sorry about the confusion.
