### ISSUE TITLE
Getting error while validating - We were unable to validate the function.

### ISSUE THREAD

**Issue by dharampal** [Azure/functionschallenge#31]
UserContextId:79c08370-0916-47e3-81e8-75a8d3fab6ba, 
UniqueId:f820e2d8-101e-4126-a233-03061644e04b. 
StackTrace
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference at CallSite.Target(Closure , CallSite , Object ) at Submission#0.d__15.MoveNext() in :line 49

However there is not code at line# 49.

**Comment by fashaikh** [comment]
When your Step2  function is POSTed to with 
```javascript

{ key = ac7a8722-2ba8-4b29-95d7-ec8c08cfffb1 }
``` 
 It returns a 404. It seems setup for GET requests and returns  an empty ArrayOfValues

```javascript

{
    "key": null,
    "ArrayOfValues": []

}```

Please update it to return a sorted Array via POST

**Comment by fashaikh** [comment]
Please reopen if this still persists
