### ISSUE TITLE
"Share your achievement" Twitter button has wrong characters and weird link

### ISSUE THREAD

**Issue by anderaus** [Azure/functionschallenge#32]
This Twitter share button on the success screen:

![image](https://user-images.githubusercontent.com/1311807/27511635-927d2b18-5929-11e7-9f82-9082c1a451f5.png)

Adds the following text (notice the wrong hashtag characters):

![image](https://user-images.githubusercontent.com/1311807/27511637-acdd71de-5929-11e7-8e5a-dbfc31222fda.png)

Also, the "pic.twitter.com" link leads to this weird account: [pic.twitter.com/V3Bh3Z0FXm](https://pic.twitter.com/V3Bh3Z0FXm)

**Comment by fashaikh** [comment]
Thanks ! I've fixed the `$` . will see if I can update the image location to a our official twitter location. That twitter account was created by us.
