### ISSUE TITLE
cannot submit solution

### ISSUE THREAD

**Issue by PiDiBi** [Azure/functionschallenge#4]
Invalid Function Url. Url must be https:// and contain azurewebsites.net/api/

http://screencast.com/t/zpxABgARrdh

**Comment by fashaikh** [comment]
Sorry this happened @PiDiBi . 
I've updated the Regex to allow for - in the function names.
Can you retry now?

**Comment by fashaikh** [comment]
Wll close after deployment

**Comment by fashaikh** [comment]
Deployed. Please verify, and best of luck !
