### ISSUE TITLE
Azure Function Challenge : Sort Array : Step 1 Exception

### ISSUE THREAD

**Issue by ShamsulAmry** [Azure/functionschallenge#5]
My solution worked when tested using the provided input sample, but keep getting the popup error below when submitting:

> We were unable to validate the function.
> Please file an issue here, if you do not recognise the stack trace below : https://github.com/Azure/functionschallenge/issues/new with 
> UserContextId:5d8befd1-f24b-4ddc-a6ba-6564f661a845, 
> UniqueId:e258f59f-4244-4b20-a64f-f91355040b14. 
> StackTrace
> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'Newtonsoft.Json.Linq.JObject' to 'string'. An explicit conversion exists (are you missing a cast?) at CallSite.Target(Closure , CallSite , Object ) at Submission#0.d__15.MoveNext() in :line 53

**Comment by fashaikh** [comment]
Sorry this happened. 
Could you retry now? I have updated the validation to look for an `empty JObject`
