### ISSUE TITLE
Logging in doesn't work

### ISSUE THREAD

**Issue by leolorenzoluis** [Azure/functionschallenge#8]
When I try to login in https://functionschallenge.azure.com using Microsoft account, I just get redirected to the login page again. 

It tries to load it, and redirects me right away.

**Comment by fashaikh** [comment]
I see that for some reason your account logged in but the user didnt get created in our B2C directory. Unfortunately there isnt enough debug logs at this time to figure out why you are unable to login. (I see other Microsoft accounts logging in). 

Until we RCA this , is it possible to try again , using a different id: live , google or facebook ?

**Comment by fashaikh** [comment]
I am working with Azure B2C to get more logs on what happened in this case. Let me know if you are able to log in.

**Comment by leolorenzoluis** [comment]
I am able to log in now. I think it is fixed? Curios though, was the domain that I was in was just not supported in B2C directory? Was it B2C's fault or the web app itself?

**Comment by fashaikh** [comment]
Its likely the web app itself. Your account was created in B2C. 
But the webapp didnt create an entry in its database. I manually created the entry in case that was the case.
That said I havent been able to repro this behavior in my tests; the webapp created a default entry in its database if the entry is missing (first login scenario). I am following up with the B2C team to see if they have logs on what happened during the oauth dance to see if there was a hiccup in the login flow .

**Comment by leolorenzoluis** [comment]
I get redirected again when I log in...

**Comment by fashaikh** [comment]
Hmm. Could this be a browser/environment thing? 
Are you able to look at the network logs in Chrome . Hit F12 and go to Network tab, and select Preserve log. And now try to login. Does anything stand out ?

**Comment by leolorenzoluis** [comment]
I'm using Safari 10.0.1 with macOS.

I don't see any errors/warning in the log

**Comment by fashaikh** [comment]
I have looped you in on an email thread with Azure AD B2C . Lets continue the debugging there

**Comment by fashaikh** [comment]
@leolorenzoluis Feel free to reopen this issue or follow up on the email thread. I am closing this for now.

**Comment by leolorenzoluis** [comment]
I did not receive any email thread regarding the issue.

**Comment by fashaikh** [comment]
sorry. Could you email me  fashaikh at microsoft.com  and I can add you to the thread.
